MushroomIncubator/mushroom_incubator/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('profile/',views.Profile.as_view(),name = 'profile'),
]

MushroomIncubator/mushroom_incubator/mushroom_incubator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
# from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mushroom_site.urls')),
    path('accounts/', include('accounts.urls',namespace='accountsa')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mushrooms/', include('mushrooms.urls',namespace='mushroomsa'))
    

]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns=[
#         path('__debug__/',include(debug_toolbar.urls))
#     ] + urlpatterns

MushroomIncubator/mushroom_incubator/mushrooms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mushrooms'

urlpatterns = [
    path('sample/',views.exampleView,name='sample'),
    path('create/',views.CreateMushroomView.as_view(), name='create'),
    path('delete/<int:pk>/',views.DeleteMushroomView.as_view(template_name='mushrooms/delete_mushroom.html'), name='delete'),
    path('<int:pk>/',views.MushroomDetailView.as_view(), name='detail'),
    path('',views.MushroomListView.as_view(), name='list'),
]

MushroomIncubator/mushroom_incubator/mushrooms/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone

from mushroom_site.models import UserProfileInfo

from django.contrib.auth import get_user_model 
User = get_user_model() 
# Create your models here.

class Mushroom(models.Model):
    
    user = models.ForeignKey(User,related_name='mushrooms', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=24)
    
    mushroom_type = (
        ('Chanterelle','Chanterelle'),
        ('Shiitake', 'Shiitake'),
        ('Portobello', 'Portobello'),
    )

    mushroom_choices = models.CharField(max_length=30, null=True, choices=mushroom_type)

    def __str__(self):
        return f'{self.user}'

    def get_absolute_url(self):
        return reverse("mushrooms:detail", kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-created_at']

MushroomIncubator/mushroom_incubator/mushrooms/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Mushroom

class MushroomForm(forms.ModelForm):

    class Meta():
        model = Mushroom
        fields = ('title','mushroom_choices')

MushroomIncubator/mushroom_incubator/mushrooms/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404,HttpResponse, HttpRequest
from urllib.request import urlopen
import json, requests
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView, DetailView, ListView
from . import models
from .forms import MushroomForm
from .models import Mushroom

from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.

class SampleChoiceView(TemplateView):
    template_name = 'sample_choice.html'
    form_class = MushroomForm

def exampleView(request):
    auth_token = "jWL3x5xRTSLnDnXZyuXxtNiznJ8ikLAm"
    pin = "V6"
    
    apirequest = (f'http://blynk-cloud.com/{auth_token}/get/{pin}')
    r = requests.get(apirequest)
    context = {
        'hello': 'hellos',
        'num1': 1254,
        'num2': 536,
        'response': r
    }
    
    return render(request,'mushrooms/sample_choice.html', context)

class CreateMushroomView(LoginRequiredMixin, CreateView):
    fields = ('title', 'mushroom_choices')
    model = models.Mushroom

class UpdateMushroomView(UpdateView):
    fields = ('title')
    model = models.Mushroom

class DeleteMushroomView(LoginRequiredMixin, DeleteView):
    model = models.Mushroom
    success_url = reverse_lazy('accounts:profile')

class MushroomDetailView(DetailView):
    model = models.Mushroom
    template_name = 'mushrooms/mushroom_detail.html'

class MushroomListView(ListView):
    model = models.Mushroom
    template_name = 'mushrooms/mushroom_list.html'
    context_object_name = 'mushrooms'

MushroomIncubator/mushroom_incubator/mushrooms/templates/mushrooms/delete_mushroom.html
{% extends "mushroom/base.html" %}
{% block content %}

<div class="jumbotron">
    <h1>Delete {{mushroom.title}} and end progress on growing {{mushroom.mushroom_choices}}? </h1>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a class="btn btn-light" href="{% url 'mushrooms:detail' pk=mushroom.pk %}">Cancel</a>
</form>
</div>



{% endblock %}

MushroomIncubator/mushroom_incubator/mushrooms/templates/mushrooms/mushroom_detail.html
{% extends "accounts/base_profile.html" %}
{% block sidebar %}

{% load static %}

<script></script>

<div class="jumbotron">
    <h1> You are currently growing {{mushroom.mushroom_choices}} mushrooms!</h1>
    <h2>Details:</h2>
    <ul>
        <li>Time started: {{mushroom.created_at}}</li>
    </ul>
    <div class="arduino">
        <div class="arduino-mod">
            <h1>TEMP/HUM SENSOR</h1>
            <div class="ard-disp">
                <div>Target temperature(°F):<h3 id="temptarget">Here is where temperature and humidity is displayed</h3></div>
                <div>Actual temperature(°F):<h3 id="temp"></h3></div>
                <div>Target humidity(%RH):<h3 id="humtarget"></h3></div>
                <div>Actual humidity(%RH):<h3 id="hum"></h3></div>                
            </div>
            <button id="temp_hum_button">Refresh Temp/Hum</button>
        </div>
        <div class="arduino-mod">
            <h1 >C02 SENSOR</h1>
            <div class="ard-disp">
                <div>Target CO2(ppm):<h3 id="co2target"></h3></div>
                <div>Actual CO2(ppm)<h3 id="co2">Here is where carbon dioxide levels are shown</h3></div>                
            </div>
            <button id="co2_button">Refresh CO2</button>
        </div>
        <div class="arduino-mod">
            <h1>LIGHT SENSOR</h1>
            <div class="ard-disp">
                <div>Light level(Lux):<h3 id="light">Here is where the light levels are shown</h3></div>
                <h3 id="time"></h3>
            </div>
            <button id="light_button">Refresh Light</button>
        </div>
    </div>
</div>
<div class="">
    <p><a class="btn btn-danger" href="{% url 'mushrooms:delete' pk=mushroom.pk  %}">Delete</a></p>
</div>
<script src="{% static 'js/blynk.js' %}"></script>

{% endblock %}

MushroomIncubator/mushroom_incubator/mushrooms/templates/mushrooms/mushroom_form.html
{% extends "accounts/base_profile.html" %}
{% block sidebar %}

<div class="jumbotron">
    <h1>Create your mushroom</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="create" class="btn btn-primary">
    </form>

</div>

{% endblock %}

MushroomIncubator/mushroom_incubator/mushrooms/templates/mushrooms/mushroom_list.html
{% extends "accounts/base_profile.html" %}
{% block sidebar %}

<div class="jumbotron">
    <h1>Mushroom list</h1>
    <ol>
        {% for mushroom in mushrooms %}
        <h2><li><a href="{{mushroom.id}}">{{mushroom.title}}</a></li></h2>
        {% endfor %}
    </ol>
    <div class="">
        <p><a class="btn btn-primary" href="{% url 'mushrooms:create' %}">Grow new mushroom</a></p>
    </div>
</div>

{% endblock %}

MushroomIncubator/mushroom_incubator/mushrooms/templates/mushrooms/sample_choice.html
{% extends "mushroom/base.html" %}
{% load static %}
{% block content %}



<div class="jumbotron">
    <h1>Blynk</h1>
    
    <div class="container">
        <div class="Blynk" style="display: flex; flex-direction: row;">
            <h1 id="Blynk1"></h1>
            <h1 id="Blynk2"></h1>
            {{ hello }}
            {{num1}}
            {{num2}}
            {{num1|add:num2}}
        </div>
        {{response}}
        {{response2}}
    </div>

    <button id="Bbutton">Get D2 Status</button>
    <button id="Abutton">Get D4 status</button>
    <button id="Cbutton">Get both? status</button>
    
</div>
<script src="{% static 'js/blynk.js' %}"></script>

{% endblock %}

MushroomIncubator/mushroom_incubator/mushrooms/templates/mushrooms/update_mushroom.html
{% extends "mushroom/base.html" %}
{% block content %}

{% endblock %}