MushroomIncubator/mushroom_incubator/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('profile/',views.Profile.as_view(),name = 'profile'),
]

MushroomIncubator/mushroom_incubator/mushroom_incubator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
# from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mushroom_site.urls')),
    path('accounts/', include('accounts.urls',namespace='accountsa')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mushrooms/', include('mushrooms.urls',namespace='mushroomsa'))
    

]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns=[
#         path('__debug__/',include(debug_toolbar.urls))
#     ] + urlpatterns

MushroomIncubator/mushroom_incubator/mushrooms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mushrooms'

urlpatterns = [
    path('sample/',views.exampleView,name='sample'),
    path('create/',views.CreateMushroomView.as_view(), name='create'),
    path('delete/<int:pk>/',views.DeleteMushroomView.as_view(template_name='mushrooms/delete_mushroom.html'), name='delete'),
    path('<int:pk>/',views.MushroomDetailView.as_view(), name='detail'),
    path('',views.MushroomListView.as_view(), name='list'),
]

MushroomIncubator/mushroom_incubator/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

MushroomIncubator/mushroom_incubator/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

MushroomIncubator/mushroom_incubator/accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from . import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

class Profile(TemplateView):
    template_name = 'accounts/profile.html'

MushroomIncubator/mushroom_incubator/accounts/templates/accounts/base_profile.html
{% extends "mushroom/base.html" %}
{% block content %}



 <div class="sidebar">
     <ul class="nav flex-column">
        <li class="nav-item"><a class="nav-link navlink" href="{% url 'accounts:profile' %}">Profile</a></li>
        <li class="nav-item"><a class="nav-link navlink" href="{% url 'mushrooms:create' %}">Create Mushrooms</a></li>
        <li class="nav-item"><a class="nav-link navlink" href="{% url 'mushrooms:list' %}">Manage Mushrooms</a></li>
    </ul>
</div>


{% block sidebar %}
{% endblock sidebar %}
{% endblock content %}

MushroomIncubator/mushroom_incubator/accounts/templates/accounts/login.html
{% extends 'mushroom/base.html' %}

{% block content%}

<div class="container">
    <div class="jumbotron">
        <h2>Login:</h2>

        {% if form.errors %}
        <p>Username and/or password didn't match. Try again.</p>
        {% endif %}

        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Login">
            <input type="hidden" name="next" value="{{next}}">

        </form>
    </div>
</div>

{% endblock %}

MushroomIncubator/mushroom_incubator/accounts/templates/accounts/profile.html
{% extends "accounts/base_profile.html" %}
{% block sidebar %}

    <div class="Jumbotron" >
        <div class="Profile">
            <h1>COMING SOON</h1>
    
        </div> 
    </div>






{% endblock %}

MushroomIncubator/mushroom_incubator/accounts/templates/accounts/signup.html
{% extends 'mushroom/base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
            <h1>Already Registered!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>
            <!-- since we are using multimedia data that we're uploading, we use enctype="multipart/form-data" this will allow image uploading to work-->
            <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Register">
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}