MushroomIncubator/mushroom_incubator/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('profile/',views.Profile.as_view(),name = 'profile'),
]

MushroomIncubator/mushroom_incubator/mushroom_incubator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
# from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mushroom_site.urls')),
    path('accounts/', include('accounts.urls',namespace='accountsa')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mushrooms/', include('mushrooms.urls',namespace='mushroomsa'))
    

]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns=[
#         path('__debug__/',include(debug_toolbar.urls))
#     ] + urlpatterns

MushroomIncubator/mushroom_incubator/mushroom_site/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include
from . import views

handler404 = 'mushroom_site.views.view_404'



urlpatterns = [
    path('',views.indexView.as_view(),name='index'),
    path('about/',views.aboutView.as_view(),name='about'),
    path('contact/',views.contactView.as_view(),name='contact'),
    path('placeholder/',views.placeholderView.as_view(),name='placeholder'),
    path('how/',views.howView.as_view(),name='how'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mushrooms/', include('mushrooms.urls',namespace='mushrooms'))
    

]

MushroomIncubator/mushroom_incubator/mushrooms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mushrooms'

urlpatterns = [
    path('sample/',views.exampleView,name='sample'),
    path('create/',views.CreateMushroomView.as_view(), name='create'),
    path('delete/<int:pk>/',views.DeleteMushroomView.as_view(template_name='mushrooms/delete_mushroom.html'), name='delete'),
    path('<int:pk>/',views.MushroomDetailView.as_view(), name='detail'),
    path('',views.MushroomListView.as_view(), name='list'),
]

MushroomIncubator/mushroom_incubator/mushroom_site/models.py
from django.db import models
from django.urls import reverse
from django.contrib import auth


# Create your models here.
class UserProfileInfo(auth.models.User, auth.models.PermissionsMixin):

    Email = models.EmailField(max_length=254,default='')
    Username = models.CharField(max_length=256,default='')


    def get_absolute_url(self):
        return reverse("index",kwargs={'pk':self.pk})

    def __str__(self):
        return "@{}".format(self.username)

class Contact(models.Model):
    first_name = models.CharField(max_length=50,default='')
    last_name = models.CharField(max_length=50,default='')
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("index")


   

MushroomIncubator/mushroom_incubator/mushrooms/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone

from mushroom_site.models import UserProfileInfo

from django.contrib.auth import get_user_model 
User = get_user_model() 
# Create your models here.

class Mushroom(models.Model):
    
    user = models.ForeignKey(User,related_name='mushrooms', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=24)
    
    mushroom_type = (
        ('Chanterelle','Chanterelle'),
        ('Shiitake', 'Shiitake'),
        ('Portobello', 'Portobello'),
    )

    mushroom_choices = models.CharField(max_length=30, null=True, choices=mushroom_type)

    def __str__(self):
        return f'{self.user}'

    def get_absolute_url(self):
        return reverse("mushrooms:detail", kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-created_at']

MushroomIncubator/mushroom_incubator/mushroom_site/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo, Contact




class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('Username',)

class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email', 'message')

MushroomIncubator/mushroom_incubator/mushrooms/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Mushroom

class MushroomForm(forms.ModelForm):

    class Meta():
        model = Mushroom
        fields = ('title','mushroom_choices')

MushroomIncubator/mushroom_incubator/mushroom_site/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from . import forms, models
from .forms import ContactForm

# Pages
class indexView(TemplateView):
    template_name = 'index.html'


class aboutView(TemplateView):
    template_name = 'about.html'

class contactView(CreateView):
    template_name = 'contact.html'
    redirect_field_name = 'index.html'
    form_class = forms.ContactForm

    

class placeholderView(TemplateView):
    template_name = 'placeholder.html'

class howView(TemplateView):
    template_name = 'how.html'

def view_404(request, *args, **kwargs):
    
    return render(request, 'mushroom/404.html')

MushroomIncubator/mushroom_incubator/mushrooms/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404,HttpResponse, HttpRequest
from urllib.request import urlopen
import json, requests
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView, DetailView, ListView
from . import models
from .forms import MushroomForm
from .models import Mushroom

from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.

class SampleChoiceView(TemplateView):
    template_name = 'sample_choice.html'
    form_class = MushroomForm

def exampleView(request):
    auth_token = "jWL3x5xRTSLnDnXZyuXxtNiznJ8ikLAm"
    pin = "V6"
    
    apirequest = (f'http://blynk-cloud.com/{auth_token}/get/{pin}')
    r = requests.get(apirequest)
    context = {
        'hello': 'hellos',
        'num1': 1254,
        'num2': 536,
        'response': r
    }
    
    return render(request,'mushrooms/sample_choice.html', context)

class CreateMushroomView(LoginRequiredMixin, CreateView):
    fields = ('title', 'mushroom_choices')
    model = models.Mushroom

class UpdateMushroomView(UpdateView):
    fields = ('title')
    model = models.Mushroom

class DeleteMushroomView(LoginRequiredMixin, DeleteView):
    model = models.Mushroom
    success_url = reverse_lazy('accounts:profile')

class MushroomDetailView(DetailView):
    model = models.Mushroom
    template_name = 'mushrooms/mushroom_detail.html'

class MushroomListView(ListView):
    model = models.Mushroom
    template_name = 'mushrooms/mushroom_list.html'
    context_object_name = 'mushrooms'

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/about.html
{% extends "mushroom/base.html" %}
{% block content %}
<div class="jumbotron aboutjumbo">
    <h1>We are Team 5</h1>
    <div class="aboutimage">
        <img src="../static/mush_pics/Group Photo.jpg" alt="" style="margin-bottom: initial; width: 100%;border-radius: 10px;">
    </div>
    <p>Mushrooms are a big part of our lives, where they serve a variety of roles.</p>
</div>

{% endblock %}

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/arduino.html
<pre>
    <font color="#95a5a6">&#47;*</font>
    <font color="#95a5a6"> &nbsp;Blink</font>
    <font color="#95a5a6"></font>
    <font color="#95a5a6"> &nbsp;Turns an LED on for one second, then off for one second, repeatedly.</font>
    <font color="#95a5a6"></font>
    <font color="#95a5a6"> &nbsp;Most Arduinos have an on-board LED you can control. On the UNO, MEGA and ZERO</font>
    <font color="#95a5a6"> &nbsp;it is attached to digital pin 13, on MKR1000 on pin 6. LED_BUILTIN is set to</font>
    <font color="#95a5a6"> &nbsp;the correct LED pin independent of which board is used.</font>
    <font color="#95a5a6"> &nbsp;If you want to know what pin the on-board LED is connected to on your Arduino</font>
    <font color="#95a5a6"> &nbsp;model, check the Technical Specs of your board at:</font>
    <font color="#95a5a6"> &nbsp;</font><u><font color="#95a5a6">https:&#47;&#47;www.arduino.cc&#47;en&#47;Main&#47;Products</font></u><font color="#95a5a6"></font>
    <font color="#95a5a6"></font>
    <font color="#95a5a6"> &nbsp;modified 8 May 2014</font>
    <font color="#95a5a6"> &nbsp;by Scott Fitzgerald</font>
    <font color="#95a5a6"> &nbsp;modified 2 Sep 2016</font>
    <font color="#95a5a6"> &nbsp;by Arturo Guadalupi</font>
    <font color="#95a5a6"> &nbsp;modified 8 Sep 2016</font>
    <font color="#95a5a6"> &nbsp;by Colby Newman</font>
    <font color="#95a5a6"></font>
    <font color="#95a5a6"> &nbsp;This example code is in the public domain.</font>
    <font color="#95a5a6"></font>
    <font color="#95a5a6"> &nbsp;</font><u><font color="#95a5a6">http:&#47;&#47;www.arduino.cc&#47;en&#47;Tutorial&#47;Blink</font></u><font color="#95a5a6"></font>
    <font color="#95a5a6">*&#47;</font>
    
    
    <font color="#434f54">&#47;&#47; the setup function runs once when you press reset or power the board</font>
    <font color="#00979c">int</font> <font color="#000000">ledPin</font> <font color="#434f54">=</font> <font color="#000000">13</font><font color="#000000">;</font>
    <font color="#00979c">void</font> <font color="#5e6d03">setup</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
     &nbsp;<font color="#434f54">&#47;&#47; initialize digital pin LED_BUILTIN as an output.</font>
     &nbsp;<font color="#d35400">pinMode</font><font color="#000000">(</font><font color="#000000">13</font><font color="#434f54">,</font> <font color="#00979c">OUTPUT</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">pinMode</font><font color="#000000">(</font><font color="#000000">8</font><font color="#434f54">,</font> <font color="#00979c">OUTPUT</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">pinMode</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">OUTPUT</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">pinMode</font><font color="#000000">(</font><font color="#000000">7</font><font color="#434f54">,</font> <font color="#00979c">INPUT</font><font color="#000000">)</font><font color="#000000">;</font>
    <font color="#000000">}</font>
    
    <font color="#434f54">&#47;&#47; the loop function runs over and over again forever</font>
    <font color="#00979c">void</font> <font color="#5e6d03">loop</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">13</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font> 
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">8</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">7</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">500</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">13</font><font color="#434f54">,</font> <font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">8</font><font color="#434f54">,</font> <font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">7</font><font color="#434f54">,</font><font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font>
     &nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">500</font><font color="#000000">)</font><font color="#000000">;</font>
     
    <font color="#000000">}</font>
    
    </pre>

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mushroom</title>

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/mushroom.css' %}">

    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand|Work+Sans&display=swap" rel="stylesheet">
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'mush_pics/favicon.ico' %}">
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark techfont">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" role="navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <!-- <div class="container">             -->
            <ul class="navbar-nav">
                <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">Mushroom Incubator</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'how' %}">How it works</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About us</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'mushrooms:sample' %}">placeholder</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" style="position: relative;margin-left: 535px;">Log Out</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:profile' %}" style="position: relative;margin-right: 10px;margin-left: 20px;">Welcome: {{ user.username }}</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}" style="position: relative;margin-left: 650px; padding-right:30px; padding-left: 30px;"><span class="glyphicon glyphicon-plus"></span>Register</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" style="position: relative;margin-right: 10px;margin-left: 20px;"><span class="glyphicon glyphicon-user"></span>Login</a></li>
                {% endif %}
            </ul>
        </div>
        <!-- </div> -->
    </nav>
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <ul class = "footer-group">
             <a class = "footer-item" href="{% url 'index' %}">Mushroom Incubator</a> 
             <a class = "footer-item" href="{% url 'how' %}">How it works</a> 
             <a class = "footer-item" href="{% url 'about' %}">About us</a> 
             <a class = "footer-item" href="{% url 'contact' %}">Contact</a> 
             <a class = "footer-item" href="{% url 'placeholder' %}">placeholder</a> 
        </ul>
    </div>
    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/contact.html
{% extends "mushroom/base.html" %}
{% block content %}
<div class="jumbotron"> 
    <div class="contact">
        <h1>Contact us Here!</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Send">
        </form>  
    </div>
    
</div>
{% endblock %}

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/create_mushroom.html
{% extends "mushroom/base.html" %}
{% block content %}
{% endblock %}

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/how.html
{% extends "mushroom/base.html" %}
{% block content %}
<div class="container">
    <div class="how">
        <h1>How it works</h1>
        <p>The mushroom incubator consists of two major components, one being the actual incubation chamber and the other the mobile application. The development of both were done in parallel. The incubation chamber is a clear chamber using plexiglass. This new approach was favorable as it facilitated the testing of component placement by being an inexpensive material and easy to manipulate.</p>
        <p>All of the following sensors and environment control modules are controlled by an Arduino. The Arduino will be programmed to have a user interface in which the user can set their preferred temperature, humidity, C02 levels and light values. To accompany the Arduino, a mobile application is used to also set and monitor the incubator environmental values.</p>

    </div>
    
</div>
    
{% endblock %}

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/index.html
{% extends "mushroom/base.html" %}
    {% load staticfiles %}
{% block content %}
    <div class="jumbotron">
        <h1>Welcome to Mushroom Incubator!</h1>



<!-- background -->
<div id="carouselCaptions" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static "mush_pics/4f82757a4698922c3e-71979158__66465.1500293551.jpg" %}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Chanterelle Mushroom</h5>
          <p>Contains fiber and are a good source of vitamins B and D</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static "mush_pics/Roasted-Portobello-Mushroom-Recipe-2-1200.jpg" %}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Portobello Mushroom</h5>
          <p>Portobello mushrooms are an excellent source of vitamins B and D</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static "mush_pics/shiitake-double-cropped.jpg" %}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Shiitake</h5>
          <p>Used for boosing the immune system, hardens arteries and contains an anti-aging agent.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
  </div>
{% endblock %}

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/mushrooms.html
{% extends "mushroom/base.html" %}
{% block content %}
{% endblock %}

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/placeholder.html
{% extends "mushroom/base.html" %}
{% block content %}
<div class="placeholder">
    <h1>This page is just a place holder</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta autem ad in ullam, fugit obcaecati repudiandae doloribus quod dolores eligendi accusamus porro atque praesentium molestias quia esse, hic quos magni?</p>

</div>
    
{% endblock %}

MushroomIncubator/mushroom_incubator/mushroom_site/templates/mushroom/registration.html
{% extends "mushroom/base.html" %}
{% block content %}

{% endblock %}